spring.application.name=SBCourseDay5-DBHomework
spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=${pass}
spring.datasource.initalSize=2
spring.datasource.maxActive=5
